kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "dotnet watch run --project FastX.Api/FastX.Api.csproj --no-hot-reload"

[services.production]

[services.production.build]
args = ["dotnet", "publish", "FastX.Api/FastX.Api.csproj", "-c", "Release", "-o", "publish"]

[services.production.run]
args = ["dotnet", "publish/FastX.Api.dll"]

[services.production.run.env]
PORT = "8080"

[services.production.health.startup]
path = "/api/healthz"
